import { KeyCode, UIKeyboardHIDUsage } from '../types'

const keyMap: Record<
KeyCode,
UIKeyboardHIDUsage | readonly UIKeyboardHIDUsage[]
> = {
  [KeyCode.Alt]: [
    UIKeyboardHIDUsage.keyboardLeftAlt,
    UIKeyboardHIDUsage.keyboardRightAlt,
  ],
  [KeyCode.ScrollLock]: UIKeyboardHIDUsage.keyboardScrollLock,
  [KeyCode.Control]: [
    UIKeyboardHIDUsage.keyboardLeftControl,
    UIKeyboardHIDUsage.keyboardRightControl,
  ],
  [KeyCode.AltGraph]: [],
  [KeyCode.NumLock]: UIKeyboardHIDUsage.keypadNumLock,
  [KeyCode.CapsLock]: UIKeyboardHIDUsage.keyboardCapsLock,
  [KeyCode.Shift]: [
    UIKeyboardHIDUsage.keyboardLeftShift,
    UIKeyboardHIDUsage.keyboardRightShift,
  ],
  Meta: [],
  PrintScreen: UIKeyboardHIDUsage.keyboardPrintScreen,
  [KeyCode.NumberPadPlus]: UIKeyboardHIDUsage.keypadPlus,
  [KeyCode.CapsLock]: UIKeyboardHIDUsage.keyboardCapsLock,
  [KeyCode.Escape]: UIKeyboardHIDUsage.keyboardEscape,
  // [ReactNativeKeysKeyCode.Space]: UIKeyboardHIDUsage.keyboardSpacebar,
  [KeyCode.Delete]: UIKeyboardHIDUsage.keyboardDeleteForward,
  [KeyCode.Backspace]:
    UIKeyboardHIDUsage.keyboardDeleteOrBackspace,
  [KeyCode.Enter]: UIKeyboardHIDUsage.keyboardReturnOrEnter,
  [KeyCode.Tab]: UIKeyboardHIDUsage.keyboardTab,
  [KeyCode.PageUp]: UIKeyboardHIDUsage.keyboardPageUp,
  [KeyCode.PageDown]: UIKeyboardHIDUsage.keyboardPageDown,
  [KeyCode.End]: UIKeyboardHIDUsage.keyboardEnd,
  [KeyCode.Home]: UIKeyboardHIDUsage.keyboardHome,
  [KeyCode.ArrowLeft]: UIKeyboardHIDUsage.keyboardLeftArrow,
  [KeyCode.ArrowUp]: UIKeyboardHIDUsage.keyboardUpArrow,
  [KeyCode.ArrowRight]: UIKeyboardHIDUsage.keyboardRightArrow,
  [KeyCode.ArrowDown]: UIKeyboardHIDUsage.keyboardDownArrow,
  [KeyCode.Insert]: UIKeyboardHIDUsage.keyboardInsert,
  [KeyCode.Help]: UIKeyboardHIDUsage.keyboardHelp,
  [KeyCode.Mute]: UIKeyboardHIDUsage.keyboardMute,
  [KeyCode.VolumeDown]: UIKeyboardHIDUsage.keyboardVolumeDown,
  [KeyCode.VolumeUp]: UIKeyboardHIDUsage.keyboardVolumeUp,
  // [ReactNativeKeysKeyCode.Comma]: UIKeyboardHIDUsage.keyboardComma,
  // [ReactNativeKeysKeyCode.Period]: UIKeyboardHIDUsage.keyboardPeriod,
  [KeyCode.Key0]: UIKeyboardHIDUsage.keyboard0,
  [KeyCode.Key1]: UIKeyboardHIDUsage.keyboard1,
  [KeyCode.Key2]: UIKeyboardHIDUsage.keyboard2,
  [KeyCode.Key3]: UIKeyboardHIDUsage.keyboard3,
  [KeyCode.Key4]: UIKeyboardHIDUsage.keyboard4,
  [KeyCode.Key5]: UIKeyboardHIDUsage.keyboard5,
  [KeyCode.Key6]: UIKeyboardHIDUsage.keyboard6,
  [KeyCode.Key7]: UIKeyboardHIDUsage.keyboard7,
  [KeyCode.Key8]: UIKeyboardHIDUsage.keyboard8,
  [KeyCode.Key9]: UIKeyboardHIDUsage.keyboard9,
  [KeyCode.KeyA]: UIKeyboardHIDUsage.keyboardA,
  [KeyCode.KeyB]: UIKeyboardHIDUsage.keyboardB,
  [KeyCode.KeyC]: UIKeyboardHIDUsage.keyboardC,
  [KeyCode.KeyD]: UIKeyboardHIDUsage.keyboardD,
  [KeyCode.KeyE]: UIKeyboardHIDUsage.keyboardE,
  [KeyCode.KeyF]: UIKeyboardHIDUsage.keyboardF,
  [KeyCode.KeyG]: UIKeyboardHIDUsage.keyboardG,
  [KeyCode.KeyH]: UIKeyboardHIDUsage.keyboardH,
  [KeyCode.KeyI]: UIKeyboardHIDUsage.keyboardI,
  [KeyCode.KeyJ]: UIKeyboardHIDUsage.keyboardJ,
  [KeyCode.KeyK]: UIKeyboardHIDUsage.keyboardK,
  [KeyCode.KeyL]: UIKeyboardHIDUsage.keyboardL,
  [KeyCode.KeyM]: UIKeyboardHIDUsage.keyboardM,
  [KeyCode.KeyN]: UIKeyboardHIDUsage.keyboardN,
  [KeyCode.KeyO]: UIKeyboardHIDUsage.keyboardO,
  [KeyCode.KeyP]: UIKeyboardHIDUsage.keyboardP,
  [KeyCode.KeyQ]: UIKeyboardHIDUsage.keyboardQ,
  [KeyCode.KeyR]: UIKeyboardHIDUsage.keyboardR,
  [KeyCode.KeyS]: UIKeyboardHIDUsage.keyboardS,
  [KeyCode.KeyT]: UIKeyboardHIDUsage.keyboardT,
  [KeyCode.KeyU]: UIKeyboardHIDUsage.keyboardU,
  [KeyCode.KeyV]: UIKeyboardHIDUsage.keyboardV,
  [KeyCode.KeyW]: UIKeyboardHIDUsage.keyboardW,
  [KeyCode.KeyX]: UIKeyboardHIDUsage.keyboardX,
  [KeyCode.KeyY]: UIKeyboardHIDUsage.keyboardY,
  [KeyCode.KeyZ]: UIKeyboardHIDUsage.keyboardZ,
  [KeyCode.Pause]: UIKeyboardHIDUsage.keyboardPause,
  [KeyCode.F1]: UIKeyboardHIDUsage.keyboardF1,
  [KeyCode.F2]: UIKeyboardHIDUsage.keyboardF2,
  [KeyCode.F3]: UIKeyboardHIDUsage.keyboardF3,
  [KeyCode.F4]: UIKeyboardHIDUsage.keyboardF4,
  [KeyCode.F5]: UIKeyboardHIDUsage.keyboardF5,
  [KeyCode.F6]: UIKeyboardHIDUsage.keyboardF6,
  [KeyCode.F7]: UIKeyboardHIDUsage.keyboardF7,
  [KeyCode.F8]: UIKeyboardHIDUsage.keyboardF8,
  [KeyCode.F9]: UIKeyboardHIDUsage.keyboardF9,
  [KeyCode.F10]: UIKeyboardHIDUsage.keyboardF10,
  [KeyCode.F11]: UIKeyboardHIDUsage.keyboardF11,
  [KeyCode.F12]: UIKeyboardHIDUsage.keyboardF12,
  [KeyCode.F13]: UIKeyboardHIDUsage.keyboardF13,
  [KeyCode.F14]: UIKeyboardHIDUsage.keyboardF14,
  [KeyCode.F15]: UIKeyboardHIDUsage.keyboardF15,
  [KeyCode.F16]: UIKeyboardHIDUsage.keyboardF16,
  [KeyCode.F17]: UIKeyboardHIDUsage.keyboardF17,
  [KeyCode.F18]: UIKeyboardHIDUsage.keyboardF18,
  [KeyCode.F19]: UIKeyboardHIDUsage.keyboardF19,
  [KeyCode.F20]: UIKeyboardHIDUsage.keyboardF20,
  [KeyCode.Find]: UIKeyboardHIDUsage.keyboardFind,
  [KeyCode.Redo]: UIKeyboardHIDUsage.keyboardAgain,
  [KeyCode.Stop]: UIKeyboardHIDUsage.keyboardStop,
  [KeyCode.Cut]: UIKeyboardHIDUsage.keyboardCut,
  [KeyCode.Paste]: UIKeyboardHIDUsage.keyboardPaste,
  [KeyCode.Undo]: UIKeyboardHIDUsage.keyboardUndo,
  [KeyCode.Copy]: UIKeyboardHIDUsage.keyboardCopy,
  [KeyCode.CapsLock]: UIKeyboardHIDUsage.keyboardCapsLock,
}

const mapIosKeyCode = (
  keyCode?: UIKeyboardHIDUsage,
): KeyCode | null => (
  (Object.keys(keyMap).find((k) => {
    const val = keyMap[k as KeyCode]
    return Array.isArray(val) && keyCode ? val.includes(keyCode) : val === keyCode
  }) as unknown as KeyCode) || null
)

export default mapIosKeyCode
