import { ReactNativeKeysKeyCode, UIKeyboardHIDUsage } from '../types'

const keyMap: Record<
ReactNativeKeysKeyCode,
UIKeyboardHIDUsage | readonly UIKeyboardHIDUsage[]
> = {
  [ReactNativeKeysKeyCode.Alt]: [
    UIKeyboardHIDUsage.keyboardLeftAlt,
    UIKeyboardHIDUsage.keyboardRightAlt,
  ],
  [ReactNativeKeysKeyCode.ScrollLock]: UIKeyboardHIDUsage.keyboardScrollLock,
  [ReactNativeKeysKeyCode.Control]: [
    UIKeyboardHIDUsage.keyboardLeftControl,
    UIKeyboardHIDUsage.keyboardRightControl,
  ],
  [ReactNativeKeysKeyCode.AltGraph]: [],
  [ReactNativeKeysKeyCode.NumLock]: UIKeyboardHIDUsage.keypadNumLock,
  [ReactNativeKeysKeyCode.CapsLock]: UIKeyboardHIDUsage.keyboardCapsLock,
  [ReactNativeKeysKeyCode.Shift]: [
    UIKeyboardHIDUsage.keyboardLeftShift,
    UIKeyboardHIDUsage.keyboardRightShift,
  ],
  Meta: [],
  PrintScreen: UIKeyboardHIDUsage.keyboardPrintScreen,
  [ReactNativeKeysKeyCode.NumberPadPlus]: UIKeyboardHIDUsage.keypadPlus,
  [ReactNativeKeysKeyCode.CapsLock]: UIKeyboardHIDUsage.keyboardCapsLock,
  [ReactNativeKeysKeyCode.Escape]: UIKeyboardHIDUsage.keyboardEscape,
  // [ReactNativeKeysKeyCode.Space]: UIKeyboardHIDUsage.keyboardSpacebar,
  [ReactNativeKeysKeyCode.Delete]: UIKeyboardHIDUsage.keyboardDeleteForward,
  [ReactNativeKeysKeyCode.Backspace]:
    UIKeyboardHIDUsage.keyboardDeleteOrBackspace,
  [ReactNativeKeysKeyCode.Enter]: UIKeyboardHIDUsage.keyboardReturnOrEnter,
  [ReactNativeKeysKeyCode.Tab]: UIKeyboardHIDUsage.keyboardTab,
  [ReactNativeKeysKeyCode.PageUp]: UIKeyboardHIDUsage.keyboardPageUp,
  [ReactNativeKeysKeyCode.PageDown]: UIKeyboardHIDUsage.keyboardPageDown,
  [ReactNativeKeysKeyCode.End]: UIKeyboardHIDUsage.keyboardEnd,
  [ReactNativeKeysKeyCode.Home]: UIKeyboardHIDUsage.keyboardHome,
  [ReactNativeKeysKeyCode.ArrowLeft]: UIKeyboardHIDUsage.keyboardLeftArrow,
  [ReactNativeKeysKeyCode.ArrowUp]: UIKeyboardHIDUsage.keyboardUpArrow,
  [ReactNativeKeysKeyCode.ArrowRight]: UIKeyboardHIDUsage.keyboardRightArrow,
  [ReactNativeKeysKeyCode.ArrowDown]: UIKeyboardHIDUsage.keyboardDownArrow,
  [ReactNativeKeysKeyCode.Insert]: UIKeyboardHIDUsage.keyboardInsert,
  [ReactNativeKeysKeyCode.Help]: UIKeyboardHIDUsage.keyboardHelp,
  [ReactNativeKeysKeyCode.Mute]: UIKeyboardHIDUsage.keyboardMute,
  [ReactNativeKeysKeyCode.VolumeDown]: UIKeyboardHIDUsage.keyboardVolumeDown,
  [ReactNativeKeysKeyCode.VolumeUp]: UIKeyboardHIDUsage.keyboardVolumeUp,
  // [ReactNativeKeysKeyCode.Comma]: UIKeyboardHIDUsage.keyboardComma,
  // [ReactNativeKeysKeyCode.Period]: UIKeyboardHIDUsage.keyboardPeriod,
  [ReactNativeKeysKeyCode.Key0]: UIKeyboardHIDUsage.keyboard0,
  [ReactNativeKeysKeyCode.Key1]: UIKeyboardHIDUsage.keyboard1,
  [ReactNativeKeysKeyCode.Key2]: UIKeyboardHIDUsage.keyboard2,
  [ReactNativeKeysKeyCode.Key3]: UIKeyboardHIDUsage.keyboard3,
  [ReactNativeKeysKeyCode.Key4]: UIKeyboardHIDUsage.keyboard4,
  [ReactNativeKeysKeyCode.Key5]: UIKeyboardHIDUsage.keyboard5,
  [ReactNativeKeysKeyCode.Key6]: UIKeyboardHIDUsage.keyboard6,
  [ReactNativeKeysKeyCode.Key7]: UIKeyboardHIDUsage.keyboard7,
  [ReactNativeKeysKeyCode.Key8]: UIKeyboardHIDUsage.keyboard8,
  [ReactNativeKeysKeyCode.Key9]: UIKeyboardHIDUsage.keyboard9,
  [ReactNativeKeysKeyCode.KeyA]: UIKeyboardHIDUsage.keyboardA,
  [ReactNativeKeysKeyCode.KeyB]: UIKeyboardHIDUsage.keyboardB,
  [ReactNativeKeysKeyCode.KeyC]: UIKeyboardHIDUsage.keyboardC,
  [ReactNativeKeysKeyCode.KeyD]: UIKeyboardHIDUsage.keyboardD,
  [ReactNativeKeysKeyCode.KeyE]: UIKeyboardHIDUsage.keyboardE,
  [ReactNativeKeysKeyCode.KeyF]: UIKeyboardHIDUsage.keyboardF,
  [ReactNativeKeysKeyCode.KeyG]: UIKeyboardHIDUsage.keyboardG,
  [ReactNativeKeysKeyCode.KeyH]: UIKeyboardHIDUsage.keyboardH,
  [ReactNativeKeysKeyCode.KeyI]: UIKeyboardHIDUsage.keyboardI,
  [ReactNativeKeysKeyCode.KeyJ]: UIKeyboardHIDUsage.keyboardJ,
  [ReactNativeKeysKeyCode.KeyK]: UIKeyboardHIDUsage.keyboardK,
  [ReactNativeKeysKeyCode.KeyL]: UIKeyboardHIDUsage.keyboardL,
  [ReactNativeKeysKeyCode.KeyM]: UIKeyboardHIDUsage.keyboardM,
  [ReactNativeKeysKeyCode.KeyN]: UIKeyboardHIDUsage.keyboardN,
  [ReactNativeKeysKeyCode.KeyO]: UIKeyboardHIDUsage.keyboardO,
  [ReactNativeKeysKeyCode.KeyP]: UIKeyboardHIDUsage.keyboardP,
  [ReactNativeKeysKeyCode.KeyQ]: UIKeyboardHIDUsage.keyboardQ,
  [ReactNativeKeysKeyCode.KeyR]: UIKeyboardHIDUsage.keyboardR,
  [ReactNativeKeysKeyCode.KeyS]: UIKeyboardHIDUsage.keyboardS,
  [ReactNativeKeysKeyCode.KeyT]: UIKeyboardHIDUsage.keyboardT,
  [ReactNativeKeysKeyCode.KeyU]: UIKeyboardHIDUsage.keyboardU,
  [ReactNativeKeysKeyCode.KeyV]: UIKeyboardHIDUsage.keyboardV,
  [ReactNativeKeysKeyCode.KeyW]: UIKeyboardHIDUsage.keyboardW,
  [ReactNativeKeysKeyCode.KeyX]: UIKeyboardHIDUsage.keyboardX,
  [ReactNativeKeysKeyCode.KeyY]: UIKeyboardHIDUsage.keyboardY,
  [ReactNativeKeysKeyCode.KeyZ]: UIKeyboardHIDUsage.keyboardZ,
  [ReactNativeKeysKeyCode.Pause]: UIKeyboardHIDUsage.keyboardPause,
  [ReactNativeKeysKeyCode.F1]: UIKeyboardHIDUsage.keyboardF1,
  [ReactNativeKeysKeyCode.F2]: UIKeyboardHIDUsage.keyboardF2,
  [ReactNativeKeysKeyCode.F3]: UIKeyboardHIDUsage.keyboardF3,
  [ReactNativeKeysKeyCode.F4]: UIKeyboardHIDUsage.keyboardF4,
  [ReactNativeKeysKeyCode.F5]: UIKeyboardHIDUsage.keyboardF5,
  [ReactNativeKeysKeyCode.F6]: UIKeyboardHIDUsage.keyboardF6,
  [ReactNativeKeysKeyCode.F7]: UIKeyboardHIDUsage.keyboardF7,
  [ReactNativeKeysKeyCode.F8]: UIKeyboardHIDUsage.keyboardF8,
  [ReactNativeKeysKeyCode.F9]: UIKeyboardHIDUsage.keyboardF9,
  [ReactNativeKeysKeyCode.F10]: UIKeyboardHIDUsage.keyboardF10,
  [ReactNativeKeysKeyCode.F11]: UIKeyboardHIDUsage.keyboardF11,
  [ReactNativeKeysKeyCode.F12]: UIKeyboardHIDUsage.keyboardF12,
  [ReactNativeKeysKeyCode.F13]: UIKeyboardHIDUsage.keyboardF13,
  [ReactNativeKeysKeyCode.F14]: UIKeyboardHIDUsage.keyboardF14,
  [ReactNativeKeysKeyCode.F15]: UIKeyboardHIDUsage.keyboardF15,
  [ReactNativeKeysKeyCode.F16]: UIKeyboardHIDUsage.keyboardF16,
  [ReactNativeKeysKeyCode.F17]: UIKeyboardHIDUsage.keyboardF17,
  [ReactNativeKeysKeyCode.F18]: UIKeyboardHIDUsage.keyboardF18,
  [ReactNativeKeysKeyCode.F19]: UIKeyboardHIDUsage.keyboardF19,
  [ReactNativeKeysKeyCode.F20]: UIKeyboardHIDUsage.keyboardF20,
  [ReactNativeKeysKeyCode.Find]: UIKeyboardHIDUsage.keyboardFind,
  [ReactNativeKeysKeyCode.Redo]: UIKeyboardHIDUsage.keyboardAgain,
  [ReactNativeKeysKeyCode.Stop]: UIKeyboardHIDUsage.keyboardStop,
  [ReactNativeKeysKeyCode.Cut]: UIKeyboardHIDUsage.keyboardCut,
  [ReactNativeKeysKeyCode.Paste]: UIKeyboardHIDUsage.keyboardPaste,
  [ReactNativeKeysKeyCode.Undo]: UIKeyboardHIDUsage.keyboardUndo,
  [ReactNativeKeysKeyCode.Copy]: UIKeyboardHIDUsage.keyboardCopy,
  [ReactNativeKeysKeyCode.CapsLock]: UIKeyboardHIDUsage.keyboardCapsLock,
}

const mapIosKeyCode = (
  keyCode?: UIKeyboardHIDUsage,
): ReactNativeKeysKeyCode | null => (
  (Object.keys(keyMap).find((k) => {
    const val = keyMap[k]
    return Array.isArray(val) && keyCode ? val.includes(keyCode) : val === keyCode
  }) as unknown as ReactNativeKeysKeyCode) || null
)

export default mapIosKeyCode
